name: antdesign_icons
description: AntDesign Icons implementation for dart projects.
version: 0.0.2
homepage: https://github.com/elkhayder/anticons
repository: https://github.com/elkhayder/anticons

environment:
   sdk: ">=2.12.0 <3.0.0"
   flutter: ">=1.17.0"

dependencies:
   flutter:
      sdk: flutter

dev_dependencies:
   flutter_test:
      sdk: flutter

flutter:
   fonts:
      - family: AntIcons
        fonts:
           - asset: font/ant_icons.ttf
